### ISSUE TITLE
[REFACTOR] 코드 리팩토링

### ISSUE THREAD

**Issue by seuriseuljjeok** [Team-Going/Going-iOS#194]
## 🛠 Issue

- 할일 추가 뷰컨의 뷰들을 분리하겠습니다.
- 코드 레이아웃 수정

## 📝 To-do
- [x] 할일 추가 뷰컨 뷰 분리
- [x] 코드 레이아웃 수정

**Comment by binisnil** [comment]
하암 놀러와떠욤◠‿◠ 사랑해❤️

**Comment by seuriseuljjeok** [comment]
> 하암 놀러와떠욤◠‿◠ 사랑해❤️

웅 나도💕
